apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-Deployment
  namespace: online-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: mern-backend
          image: janithad/mern-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: mongo_connection
              value: "mongodb://root:password@mongo-service:27017/"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: online-store
spec:
  selector:
    app: mern-backend
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP

  


